#!/usr/bin/python
# Filename: class_init.py

class Person:
    def __init__(self, na):
        self.nam = na
    def sayHi(self):
        print 'Hello, my name is', self.nam

p = Person('zhaoczrrrrr')
p.sayHi()

# This short example can also be written as Person('Swaroop').sayHi()
